---
# tasks file for appserver

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: remove the java-1.7.0 package
  yum:
    name: java-1.7.0-openjdk
    state: absent


- name: Installing the java-1.8.0-openjdk package
  yum:
    name: java-1.8.0-openjdk-devel
    state: present

- name: Download sonar.repo
  get_url:
    url: http://downloads.sourceforge.net/project/sonar-pkg/rpm/sonar.repo
    dest: /etc/yum.repos.d/sonar.repo
    mode: 0440

- name: installing sonar
  yum:
    name: sonar
    state: present

- file:
    path: /etc/init.d/sonar
    owner: root
    group: root
    mode: 0777

- name: Ensure Sonar is running and set to start on boot.
  service: name=sonar state=started enabled=yes

- name: Aadding iptable rule
  command: iptables -I INPUT 1 -p tcp --dport 9000 -j ACCEPT -m comment --comment "port 9000"
  command: iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT
  command: iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 9000
